### ISSUE TITLE
TOML.print produces invalid/unparsable output

### ISSUE THREAD

**Issue by tecosaur** [JuliaLang/TOML.jl#39]
I'm trying to represent what's probably a slightly more complex structure than is usually found it TOML.

```toml
[[dataset.loader]]
driver = "nested"
loaders = ["gzip", { driver = "csv", args = {delim = "\t"}}]
```

This is parsed without issue, but `TOML.print` produces invalid output.

```toml
[[dataset.loader]]
driver = "nested"
loaders = ["gzip", driver = "csv"

[args]
delim = "\t"
]
```

This seems to be the MWE to produce an error from originally valid TOML:
```julia
TOML.parse(sprint(TOML.print, TOML.parse("x = [1, { a = 2, b = 3}]")))
```

This failure to round-trip is particularly problematic for my use case, as I'm trying to have a file which is written by machine/human and automatically updated.
