### ISSUE TITLE
Output style request: use inline dicts when brevity is improved

### ISSUE THREAD

**Issue by tecosaur** [JuliaLang/TOML.jl#42]
###### ( rewording of a comment in #40 )

Despite best efforts, in some cases the structure being represented can become somewhat nested. In such situations, the fact that `TOML.print` *always* writes dicts out as `[key.subkey...] thing=val` can actually make the readability worse.

Here's a practical example from a file I have, processed we have:
```toml
[["GTEx v8 transcript tpm"]]
stuff="..."
    [["GTEx v8 transcript tpm".loader]]
    stuff="..."
        [["GTEx v8 transcript tpm".loader.loaders]]
        driver = "csv"
        args = { header = 3 }
```
this becomes (via a parsing round-trip)
```toml
[["GTEx v8 transcript tpm"]]
stuff="..."
    [["GTEx v8 transcript tpm".loader]]
    stuff="..."
        [["GTEx v8 transcript tpm".loader.loaders]]
        driver = "csv"
        
            ["GTEx v8 transcript tpm".loader.loaders.args]
            header = 3
```
which I think is quite simply harder to read.

I'd think a heuristic along the lines of "if number of key-value pairs less than (some N) and inline dict representation is <72 characters long, use an inline dict" could be quite helpful here.
